---
abstract: 'Dancer2::Plugin::Queue backend using MongoDB'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Dancer2::Plugin::Queue::Role::Test: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  HTTP::Tiny: 0
  List::Util: 0
  MongoDB: 0.45
  MooX::Types::MooseLike::Base: 0
  Test::More: 0
  Test::Roo: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Plugin-Queue-MongoDB
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dancer2::Plugin::Queue::MongoDB:
    file: lib/Dancer2/Plugin/Queue/MongoDB.pm
    version: 0.003
requires:
  Dancer2::Plugin::Queue: 0.003
  Dancer2::Plugin::Queue::Role::Queue: 0
  MongoDB: 0
  MongoDB::MongoClient: 0
  MongoDBx::Queue: 0
  Moose: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/dancer2-plugin-queue-mongodb/issues
  homepage: https://metacpan.org/release/Dancer2-Plugin-Queue-MongoDB
  repository: git://github.com/dagolden/dancer2-plugin-queue-mongodb.git
version: 0.003
